# The driver name must match the section name in /etc/odbcinst.ini.
[TrinoProd]
Description=Trino JSONDoc Lakehouse
Driver=Simba Trino ODBC Driver
Host=woko.labs.localhost.com
Port=8080
Catalog=iceberg
Schema=jsondoc
SSL=0
AuthenticationType=No Authentication
